"""Write the merged manifest module for a build that contains both games.

The merged manifest is a tiny Lua module rather than a third copy of the data:
it requires the two conversions and merges them through port/merge.lua, which
checks the ID bands (Undertale below YELLOW_BASE, Yellow at or above it). Both
conversions must already be complete; this never fabricates the missing one.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MODULE = """-- Generated by tools/merge.py. Merges the two converted games and the port's
-- cross-game travel bridge; see port/merge.lua for the ID-band invariant.
local undertale = require("generated.manifest")
local yellow = require("generated.yellow.manifest")
return require("port.merge").manifests(undertale, yellow)
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=ROOT / "generated" / "merged")
    args = parser.parse_args()

    undertale_report = ROOT / "generated" / "conversion-report.json"
    yellow_report = ROOT / "generated" / "yellow" / "conversion-report.json"
    for report in (undertale_report, yellow_report):
        if not report.is_file():
            print(f"{report} is missing: run tools/convert.py and tools/yellow_convert.py first.", file=sys.stderr)
            return 1
        data = json.loads(report.read_text())
        problems = data.get("compile_errors") or []
        if problems:
            print(f"{report}: refusing to merge a conversion with {len(problems)} compile errors.", file=sys.stderr)
            return 1
        stage = data.get("stage")
        if stage not in (None, "complete", "rooms"):
            print(f"{report}: conversion stopped at stage {stage!r}; refusing to merge a partial game.", file=sys.stderr)
            return 1
        if not (ROOT / "generated" / "manifest.lua").is_file() or not (ROOT / "generated" / "yellow" / "manifest.lua").is_file():
            print("both generated manifests must exist before merging", file=sys.stderr)
            return 1

    args.output.mkdir(parents=True, exist_ok=True)
    manifest = args.output / "manifest.lua"
    manifest.write_text(MODULE)
    yellow = json.loads(yellow_report.read_text())
    # The report groups the shared names by category, so the honest count is the
    # sum of the groups -- not len() of the mapping, which is the number of
    # categories that happen to have a collision.
    collisions = yellow.get("name_collisions_with_undertale") or {}
    total = sum(len(entries) for entries in collisions.values())
    per_category = ", ".join(f"{category} {len(entries)}" for category, entries in sorted(collisions.items()))
    print(f"Merged manifest: {manifest.relative_to(ROOT)}")
    print(f"Yellow band base: {yellow.get('yellow_base')}; "
          f"assets both games name: {total} ({per_category})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
